# Generated by Django 5.0.6 on 2025-08-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('producer', 'Producer'), ('buyer', 'Buyer'), ('regulator', 'Regulator'), ('verifier', 'Verifier')], max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
