# Generated by Django 5.0.6 on 2025-08-30 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydrogenBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('production_date', models.DateField()),
                ('certification', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydrogen_batches', to='auth1.user1')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('burned', 'Burned')], default='active', max_length=50)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_credits', to='auth1.user1')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='api.hydrogenbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('crypto', 'Crypto'), ('fiat', 'Fiat')], max_length=50)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='auth1.user1')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_id', models.AutoField(primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('mint', 'Mint'), ('transfer', 'Transfer'), ('burn', 'Burn'), ('purchase', 'Purchase')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fiat_value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tx_hash', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.credit')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to='auth1.user1')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='auth1.user1')),
            ],
        ),
    ]
